#!/usr/bin/env python3
"""
merge_paper.py — Menggabungkan section-section paper menjadi satu file.

Urutan file didefinisikan di SECTIONS. Jalankan dari root proyek:
    conda run -n tpack-research python paper/merge_paper.py [--lang en|id]

Options:
    --lang en   Merge English sections from paper/en/ (default)
    --lang id   Merge Indonesian sections from paper/id/

Output:
    paper/paper_full_en.md  (for English)
    paper/paper_full_id.md  (for Indonesian)
"""

import argparse
import re
from pathlib import Path

PAPER_DIR = Path(__file__).parent

# Urutan section sesuai IMRAD
SECTIONS = [
    "00_front_matter.md",
    "01_introduction.md",
    "02_literature_review.md",
    "03_methods.md",
    "04_results.md",
    "05_discussion.md",
    "06_conclusion.md",
    "07_references.md",
]

LANG_CONFIG = {
    "en": {
        "subdir": "en",
        "output": "paper_full_en.md",
        "todo_text": "<!-- TODO: {fname} not yet written -->",
        "header_template": (
            "<!-- Auto-generated by merge_paper.py (lang={lang}) | "
            "Total: ~{words} words | "
            "Sections: {found}/{total} -->\n\n"
        ),
    },
    "id": {
        "subdir": "id",
        "output": "paper_full_id.md",
        "todo_text": "<!-- TODO: {fname} belum ditulis -->",
        "header_template": (
            "<!-- Dibuat otomatis oleh merge_paper.py (lang={lang}) | "
            "Total: ~{words} kata | "
            "Seksi: {found}/{total} -->\n\n"
        ),
    },
}


def adjust_image_paths(content: str, from_subdir: bool = True) -> str:
    """
    Adjust relative image paths when merging sections.

    When merging from paper/en/ or paper/id/ into paper/paper_full_*.md,
    image paths need adjustment:
    - From subdir (paper/en/): ../../outputs/ → ../outputs/
    - Already correct: ../outputs/ → ../outputs/ (no change)
    - model.png stays as model.png (same directory after merge)

    Args:
        content: Section content with markdown image links
        from_subdir: If True, adjust paths from subdirectory to parent

    Returns:
        Content with adjusted image paths
    """
    if not from_subdir:
        return content

    # Pattern: ![caption](path)
    # Replace ../../ with ../ for outputs paths
    # This handles cases where source files use ../../outputs/
    content = re.sub(
        r"!\[([^\]]*)\]\(\.\./\.\./outputs/", r"![\1](../outputs/", content
    )

    return content


def merge(lang: str = "en") -> None:
    """Merge section files into a single paper file."""
    if lang not in LANG_CONFIG:
        raise ValueError(f"Unsupported language: {lang}. Use 'en' or 'id'.")

    config = LANG_CONFIG[lang]
    section_dir = PAPER_DIR / config["subdir"]
    output_path = PAPER_DIR / config["output"]

    print(f"\nMerging {lang.upper()} sections from: {section_dir}")
    print("-" * 50)

    parts: list[str] = []
    found_count = 0

    for fname in SECTIONS:
        fpath = section_dir / fname
        if fpath.exists():
            content = fpath.read_text(encoding="utf-8").strip()
            # Adjust image paths when merging from subdirectory
            content = adjust_image_paths(content, from_subdir=True)
            parts.append(content)
            word_count = len(content.split())
            print(f"  [OK] {fname} ({word_count} words)")
            found_count += 1
        else:
            parts.append(config["todo_text"].format(fname=fname))
            print(f"  [--] {fname} (not found)")

    merged = "\n\n---\n\n".join(parts)

    # Word count
    total_words = len(merged.split())

    # Header
    header = config["header_template"].format(
        lang=lang,
        words=total_words,
        found=found_count,
        total=len(SECTIONS),
    )

    output_path.write_text(header + merged, encoding="utf-8")
    print("-" * 50)
    print(f"  => {output_path} ({total_words} words)")


def merge_all() -> None:
    """Merge both language versions."""
    for lang in LANG_CONFIG:
        merge(lang)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Merge paper sections into a single file.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python paper/merge_paper.py            # Merge English (default)
  python paper/merge_paper.py --lang en  # Merge English
  python paper/merge_paper.py --lang id  # Merge Indonesian
  python paper/merge_paper.py --all      # Merge both languages
        """,
    )
    parser.add_argument(
        "--lang",
        choices=["en", "id"],
        default="en",
        help="Language version to merge (default: en)",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Merge all language versions",
    )

    args = parser.parse_args()

    if args.all:
        merge_all()
    else:
        merge(args.lang)


if __name__ == "__main__":
    main()
