#!/usr/bin/env python3
"""
merge_paper.py — Menggabungkan section-section paper menjadi satu file.

Urutan file didefinisikan di SECTIONS. Jalankan dari root proyek:
    conda run -n tpack-research python paper/merge_paper.py

Output: paper/paper_full.md
"""

from pathlib import Path

PAPER_DIR = Path(__file__).parent
OUTPUT = PAPER_DIR / "paper_full.md"

# Urutan section sesuai IMRAD
SECTIONS = [
    "00_front_matter.md",
    "01_introduction.md",
    "02_literature_review.md",
    "03_methods.md",
    "04_results.md",
    "05_discussion.md",
    "06_conclusion.md",
    "07_references.md",
]


def merge() -> None:
    parts: list[str] = []

    for fname in SECTIONS:
        fpath = PAPER_DIR / fname
        if fpath.exists():
            content = fpath.read_text(encoding="utf-8").strip()
            parts.append(content)
            print(f"  [OK] {fname} ({len(content.split())} words)")
        else:
            parts.append(f"<!-- TODO: {fname} belum ditulis -->")
            print(f"  [--] {fname} (belum ada)")

    merged = "\n\n---\n\n".join(parts)

    # Word count
    total_words = len(merged.split())

    # Header
    header = (
        f"<!-- Auto-generated by merge_paper.py | "
        f"Total: ~{total_words} words | "
        f"Sections: {sum(1 for f in SECTIONS if (PAPER_DIR / f).exists())}/{len(SECTIONS)} -->\n\n"
    )

    OUTPUT.write_text(header + merged, encoding="utf-8")
    print(f"\n  => {OUTPUT} ({total_words} words)")


if __name__ == "__main__":
    merge()
